# --- Base de donnees --------------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/reservia_db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username =root
spring.datasource.password =
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA --------------------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
#spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# --- Hibernate --------------------------------------------------
logging.level.org.hibernate=error
logging.level.org.springframework.jdbc=error
logging.level.org.springframework.orm.jpa=error

# --- Cache Hibernate --------------------------------------------
#spring.jpa.properties.hibernate.cache.use_second_level_cache=true
#spring.jpa.properties.hibernate.cache.use_query_cache=true

# --- SMTP --------------------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=contact.reservia@gmail.com
spring.mail.password=zydvpoyufbmsfaul

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

stripe.api.key=${STRIPE_SECRET_KEY}
stripe.public.key=${STRIPE_PUBLIC_KEY}

# --- Upload images ----------------------------------------------
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# --- Thymeleaf --------------------------------------------------
spring.thymeleaf.cache=false

server.port=8085